### ISSUE TITLE
Put inside the funcool namespace

### ISSUE THREAD

**Issue by Alotor** [funcool/hodgepodge#3]
I was expecting to install the library as:

```
[funcool/hodgepodge "0.1.3"]
```

Instead of

```
[hodgepodge "0.1.3"]
```

**Comment by dialelo** [comment]
You're right, it'll be fixed in a minute.

**Comment by dialelo** [comment]
Should be under the funcool group id now!

**Comment by Alotor** [comment]
:+1: it was breaking the symmetry of my dependencies lol
